name: Python Build Workflow
run-name: Commit - ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call

jobs:
  Build:
    name: Running SAST [BearerCLI]
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4
         